apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2024-05-17T07:58:35Z","labels":{"app":"spring-petclinic-rest"},"name":"spring-petclinic-rest","namespace":"default","resourceVersion":"2742","uid":"372efd61-fde2-4f84-8791-da7a972845b5"},"spec":{"allocateLoadBalancerNodePorts":true,"clusterIP":"10.103.175.229","clusterIPs":["10.103.175.229"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":31956,"port":9966,"protocol":"TCP","targetPort":9966}],"selector":{"app":"spring-petclinic-rest"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2024-05-17T08:04:52Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "353"
  uid: 4ed05aa6-d729-4e87-8e3c-ae958482cfc5
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.175.229
  clusterIPs:
  - 10.103.175.229
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31956
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
